### ISSUE TITLE
Update Zermelo Card and TreeCard and Graph to properly leverage the Socket/Wrench system

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#100]
Update Zermelo Card and TreeCard and Graph to properly leverage the Socket/Wrench system

**Comment by kchapple** [comment]
@ftrotter I added this to graph, you want me to explore TreeCard, or are we still leaving that for now?

**Comment by ftrotter** [comment]
leaving that.

**Comment by ftrotter** [comment]
FYI I have tested this and it appears to work. Will improve the UX in a seperate ticket for after 1.0
