### ISSUE TITLE
Laravel 6 problem: not loading bootstrap location from config file

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#106]
When I upgraded an instance to Laravel 6, the zermelo tablular display found nothing in the BOOTSTRAP_CSS_LOCATION configuration value, despite it being set correctly in zermelobladetabular.php for all that I could tell. 

I fixed this by making a default for bootstrap to be /css/bootstrap.min.css when there is no configuration value set... (which failes more gently). Not sure why this happened or if this is a consistent problem...

-FT

**Comment by seanccsmith** [comment]
Zermelo no longer complains of missing values on install. Closing issue.
