### ISSUE TITLE
Is Zermelo causing Database Selection to break for Laravel?

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#108]
So I have noticed multiple times that when I am using other laravel functions, even for simple things, I am getting errors like this one: 

![Screen Shot 2019-10-22 at 11 04 58 PM](https://user-images.githubusercontent.com/83133/67356676-8cb5e400-f520-11e9-85ff-9404e96dfa20.png)

But I have a default database setup and 90% of the time it works just fine. 
However, when I install laravel tinker and type 

```
>>> config('database');
```
I see a bunch of stuff about the Zermelo cache/config databases there too. 

Is it possible that by installing Zermelo and setting up the different databases that I am "loosing" the original database to be selected by Laravel. Here is how to replicate..

* Install a naked instance of Laravel, in any way that is reasonable. 
* install zermelo and configure it. 
* try and install Laravel Telescope https://laravel.com/docs/6.x/telescope#installation
* Run the ./artisan migrate command and see if you get the same error I did. 

If so. you see the error message above then something about the zermelo initialization is borking the selection of the default database for Laravel. 

-FT

**Comment by ftrotter** [comment]
Well I have at least found the problem.
Line 63 of https://github.com/CareSet/Zermelo/blob/master/src/CareSet/Zermelo/Models/ZermeloDatabase.php

has the code
```php
       config(["database.connections.mysql.database" => null]);
```

And this serves to confuse Laravels selection of the underlying database in a way that cannot be simply repaired by restoring the previous value... So I have commented this line out... 

So I am sure I am introducing another issue by commenting out this code, but without it, I cannot move forward... 

-FT

**Comment by kchapple** [comment]
Thanks for digging that up Fred. I might need to think of an alternative zero-configuration method for creating and accessing the config and cache databases, but maybe just removing that line will be adequate.  I have time tomorrow and Friday to work on Careset stuff and will look at this first. 

Ken
