### ISSUE TITLE
1.0 testing scenarios

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#110]
It seems like the major refactoring process has worked for the 1.0 release.. leaving only various minor bugs around. However, the installation process still leaves a lot to be desired.. and can get to some wonky states... For that reason, lets be sure to test in the following basic deployment scenarios:

* A new cloud server, with no supporting databases (i.e. _zermelo_cache or _zermelo_config)
* uninstall on the new installation. 
* reinstall on the new installation. 
* create a second laravel virtual host on the same server..., and verify that the first instance is not trampled...
* uninstall the second installation... 
* reinstall the second installation...
* confirm that it handles the state when _zermelo_cache and _zermelo_config exist... but that the .env user/password do not have access.. 
* confirm that removing DB access to _zermelo_cache and _zermelo_config in a previously working installation work as expected.. 
* Ensure that when composer require for zermelo has been run... but the ./artisan zermelo:install command(s) have not been read, that the default report does not result in a gooblygook error but instead says "Hey you need to install the Zermelo UX files..."

After the "installation testing" has been completed, each test report in the ZTest project should be run... and pass... 

* Setup some kind of authentication middle ware for the installation of Zeremelo using the MIDDLEWARE configuration variable inside /config/zermelo.php and make sure it works...

And then I think we are ready for 1.0
-FT

**Comment by ftrotter** [comment]
done.

**Comment by ftrotter** [comment]
closed wrong issue..

**Comment by kchapple** [comment]
@ftrotter This line breaks installer because there's no column 'wrench'

Is this supposed to be wrench_label you want to impose a uinique constraint?

https://github.com/CareSet/Zermelo/blob/5187b106907f5cceac6751ae70c3ff48e3e1a7a3/database/migrations/2019_03_11_095512_create_sockets_and_wrenches.php#L82

**Comment by kchapple** [comment]
@ftrotter You make a couple references to uninstalling Zermelo instances. What "uninstall" process are you using? Do you just mean delete the Laravel app code?

**Comment by ftrotter** [comment]
I mean removing the zermelo install and other zermelo projects from composer.json and doing a composer update.

**Comment by kchapple** [comment]
That’s what I figured. I used “composed remove careset/zeemeLo*” Which has same effect. I added to the readMe.

Ken

**Comment by seanccsmith** [comment]
Attempting to make sure that we get a nice, clear error message when composer require has been run but before zermelo:install has been executed and an attempt is made to access a report through the browser. After a thorough uninstall of zermelo, and running composer require, I receive the following error on attempting to access a report in Lore Commander:

![Screen Shot 2020-05-11 at 12 29 57 PM](https://user-images.githubusercontent.com/42678849/81592368-7ae44300-9383-11ea-95b8-77413944b345.png)

Not super nice. Is this due to a bug in the error catcher, or rather due to over-zealous uninstall on my part?

**Comment by seanccsmith** [comment]
Created separate issues for bullet points 9 and 10, as these have spun into their own problems. The last point will be covered under issue #50.

**Comment by seanccsmith** [comment]
I’m confused as well about the 7th and 8th bullet points on the same card. 7 is asking to confirm that when the db credentials specified in the .env do not have access to the cache and config tables in the db, the state is handled correctly. similarly, 8 asks to remove access from a previously working installation and to confirm that it works “as expected”.

I changed the user name in the .env to something that doesn’t exist in the users list, and got this error:

![Screen Shot 2020-05-11 at 3 37 24 PM](https://user-images.githubusercontent.com/42678849/81706459-a9225b00-9435-11ea-87ef-712e8d483542.png)

am I understanding correctly that this is the correct error, and thus can check off both the 7th and 8th points?

**Comment by seanccsmith** [comment]
Remaining problems will be evaluated in their own threads.

**Comment by ftrotter** [comment]
We know that there are several errors that are going to regularly occur every time some new user installs zermelo. One of them is that access to _zermelo_config and _zermelo_cache is not enabled. Sometimes people will get this error from the command line (I think the install process is pretty good at this point at making that smooth) but sometimes, it will happen because they go to a website. I would like to have Zermelo be smart enough to check that database access to these two tables exist, and "catch" this error and display a single sentence on screen. 

"The (insert mysqlusername here) mysql user does not have permissions to the (databaes for _zermelo_cache and _zermelo_config gotten from the config file). You need to enable this access before moving forward."

Literally I want that sentence on the screen and nothing else. 

I do not want to have someone "figure out" what the most common configuration errors are when then install the system. The system should be smart enough to know "I am not installed yet". 

Sean, you should spend a little time looking at the php notions of try/catch: 
https://stackify.com/php-try-catch-php-exception-tutorial/

Regards,
-FT

**Comment by seanccsmith** [comment]
Gotcha, this makes sense now.

**Comment by seanccsmith** [comment]
Bullet points 7, 8, and 9 have a functional fix, and have been moved to their own issue for completion: https://github.com/CareSet/Zermelo/issues/119

The ZTest project has been deprecated. Middleware authentication also has its own issue: https://github.com/CareSet/Zermelo/issues/50

Everything else is QA'd and ready for rollout.
