### ISSUE TITLE
Inappropriate behavior after running composer require but before installation with zermelo:install

### ISSUE THREAD

**Issue by seanccsmith** [CareSet/Zermelo#118]
[In issue #110](https://github.com/CareSet/Zermelo/issues/110), one of the v1.0 requirements is:

"Ensure that when composer require for zermelo has been run... but the ./artisan zermelo:install command(s) have not been read, that the default report does not result in a gooblygook error but instead says "Hey you need to install the Zermelo UX files...""

After running composer require and before running zermelo:install, we do in fact get an unfriendly error:

![Screen Shot 2020-05-11 at 12 29 57 PM](https://user-images.githubusercontent.com/42678849/81705541-c571c800-9434-11ea-8d6a-c112442d5e5e.png)

This is resolved as expected by running ./artisan zermelo:install, so probably all that's missing is a nice error catch or fixing the existing one.

**Comment by kchapple** [comment]
@seanccsmith New error displays what's wrong and how to fix it. Not sure if Fred meant that we should also have an error template to display errors in a styled, pretty format for users?

![Screen Shot 2020-05-12 at 12 25 01 PM](https://user-images.githubusercontent.com/271809/81719908-ad597300-944b-11ea-9bbe-a2ed5c732ac0.png)

**Comment by ftrotter** [comment]
This is more than enough. Closing.
