### ISSUE TITLE
whitespace at bottom of report 

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#120]
<img width="572" alt="Screen Shot 2020-05-18 at 7 09 05 AM" src="https://user-images.githubusercontent.com/83133/82211554-a660b380-98d6-11ea-908a-6f9b7bcad5b7.png">

Not sure why there is this whitespace at the bottom of the page.. our tabular view should be able to take advantage of tall monitors...

**Comment by kchapple** [comment]
This was fixed and committed to the zermelobladetabular repo.

[master cfadf84] Fix whitespace at bottom of report (#120)

![Screen Shot 2020-05-20 at 2 47 14 PM](https://user-images.githubusercontent.com/271809/82485105-eb3c4400-9aa8-11ea-82d3-aaea35d1ee56.png)

**Comment by seanccsmith** [comment]
No more whitespace.
