### ISSUE TITLE
columnMap[columnMapKey] is undefined in lore report

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#122]
The full error you get when visiting this page: 
https://lore.ft1.us/Zermelo/mostReleasedArt
is:

```
TypeError: columnMap[columnMapKey] is undefined mostReleasedArt:672:5
    <anonymous> https://lore.ft1.us/Zermelo/mostReleasedArt:672
    jQuery 4
```
Unsure what would cause this error to occur, likely something to do with column settings in the report. Need to figure out what error was made in the report, and ensure that the error is caught at a higher level and expressed as something that a report-writer can understand. This is assuming it is a problem with the specific report which I assume because other tabular reports on lore.ft1.us are working well. 

-ft

**Comment by kchapple** [comment]
@seanccsmith this has been fixed
[master fea4a7c] Fixed sort order parameter bug, thro exception when parameters are wrong format (#123) (#122)

**Comment by seanccsmith** [comment]
Confirmed working now.
