### ISSUE TITLE
Bug in report table string length causing SQL error

### ISSUE THREAD

**Issue by kchapple** [CareSet/Zermelo#125]
There is a bug in the calculation that is supposed to truncate the report name so it fits in the required MYSQL table name length that doesn't truncate because it uses max() function instead of min()

![Screen Shot 2020-06-16 at 11 43 59 AM](https://user-images.githubusercontent.com/271809/84813058-5bbd7e80-afdd-11ea-8543-1c2d3072be84.png)

**Comment by kchapple** [comment]
@ftrotter @seanccsmith This bug has been fixed.

**Comment by seanccsmith** [comment]
Looks good!
