### ISSUE TITLE
GraphTest not working

### ISSUE THREAD

**Issue by kchapple** [CareSet/Zermelo#128]
Here's how the error is presented on the screen:
![Screen Shot 2020-06-19 at 11 55 18 AM](https://user-images.githubusercontent.com/271809/85153120-c8c25580-b223-11ea-8fc2-68ccfbe63574.png)

From the laravel.log, we see we are getting this exception:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'node_img' cannot be null at /home/vagrant/code/LoreCommander/vendor/laravel/framework/src/Illuminate/Database/Connection.php:463)

The solution could be either of these:
 1- The target_node column across every row in the test data is NULL, and shouldn't be.
 2- The schema that is generated on the back-end for nodes_* requires the node_img to be non-null, when in reality it should be allowed to be null sometimes. 

CREATE TABLE `nodes_TEST_GraphTest_f616b663d217a3b0b21626898aad9b08` (
  `id` int(11) NOT NULL,
  `node_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `node_name` varchar(1000) CHARACTER SET utf8 DEFAULT NULL,
  `node_size` bigint(20) DEFAULT NULL,
  `node_type` varchar(1000) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `node_group` varchar(255) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `node_latitude` decimal(17,7) NOT NULL DEFAULT '0.0000000',
  `node_longitude` decimal(17,7) NOT NULL DEFAULT '0.0000000',
  `node_json_url` varchar(2000) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `node_img` varchar(1000) CHARACTER SET utf8 NOT NULL DEFAULT ''
)

**Comment by ftrotter** [comment]
fixed.
