### ISSUE TITLE
Visual way to indicate whether caching is occuring. 

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#13]
Rather than continue to have the caching on by default vs off by default debate. (which has pros and cons either way) we should work to address the underlying usability problem with caching. 

When you are writing a report, and the data is changing underneath, and you are expecting the report contents to change, but they do not... then this creates a very hard to find bug for a report builder role who does not, should not and potentially can not understand how the caching works. 

So lets expose the following information and functionality to the default view:

* Whether the report was loaded from the cache, or by running the query
* How many times this report has been loaded from the cache
* When the cache that is powering the current data view was built 
* ~~A button to refresh the cache.~~ (this should be a different feature, later) 

Obviously depends on https://github.com/CareSet/Zermelo/issues/35

**Comment by kchapple** [comment]
this was fixed with cache indicator
