### ISSUE TITLE
automatically create the /app/Zermelo/ and create initial example report

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#2]
Should now be /app/Zermelo/ rather than /app/CareSetReports/

**Comment by ftrotter** [comment]
The example report(s) should be simple drill down study of the information_schema table.

**Comment by tmccormi** [comment]
The current install says to manually create /app/Reports/ , copy in the examples and load the DB.  I agree that the default install process should allow the "Examples" to be included.  However the database/tables should be loaded automatically on first execution of the example via a migration script I think.
