### ISSUE TITLE
make a pending indicator

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#26]
If a report is going to take time to load, that is fine... but it should tell the user with a spinner or some other indicator that things are not broken. 

I think it would be cool to allow people to choose which fontawesome spinner to use... and to use a nice big one by default: 

http://jsfiddle.net/chadkuehn/1twpzLz8/

**Comment by kchapple** [comment]
![Screen Shot 2019-10-07 at 1 37 42 PM](https://user-images.githubusercontent.com/271809/66334781-b27ba000-e907-11e9-8ccf-fedb5b296142.png)
Make pending indicator, show while headers are being generated as well as table data

**Comment by ftrotter** [comment]
Please make the pending indicator live inside the data area and not grey the background of the screen. The user should be thinking "oh, the page has loaded, but my data has not". Rather than "has this page loaded? Why is this slow?"

**Comment by ftrotter** [comment]
Also, the pending indicator will stay up even after an SQL error message has returned from the server. The pending indicator should live inside the data display area and should go away once anything is loaded to replace the data display area...

**Comment by kchapple** [comment]
[master 8703ac7] Use regular jquery datatables processing mechanism for showing loading-indicator, make show within data table, not while headers are loading, remove grey background (#26)

**Comment by ftrotter** [comment]
I think this is fixed... but the pending indicator seems to be changing the form focus away from the fields also ??? not 100% sure, but we need to make sure that when hitting the "delete" key on a form field we do not end up pressing the back button on the browser because of a field focus change due to the status indicator...

**Comment by kchapple** [comment]
I just did some quick testing and the spinner doesn't take focus away from the jquery datatables filter text-boxes in the column headers, but it may take focus away if you have an embedded form at the top that submits and reloads the entire page (it's not the spinner that's doing that though, so if that's functionality you want, this is a new issue.)

**Comment by ftrotter** [comment]
ok. closing this issue for now.
