### ISSUE TITLE
Need a way to realize that a filter has been applied

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#28]
It is too easy to forget that you have something in a particular search field and then wonder why your search is returning nothing... 

If a search restriction is so limiting that it returns no results, then we should use the results area to let the user know what filter/search criteria are being applied... perhaps with little X icons to delete the filter and search and get some more results.. .

This problem is compounded by the fact that there are two different "levels" of search.. 

Awesome feature... but it does lead to some confusing results...

**Comment by kchapple** [comment]
![Screen Shot 2019-10-07 at 12 47 27 PM](https://user-images.githubusercontent.com/271809/66331706-249cb680-e901-11e9-9175-a8c050298e21.png)
@ftrotter Added a display of what filters are applied, and a method for end-user to clear them with a click

**Comment by ftrotter** [comment]
This works, but it needs to be either all the way to the left, so that users can see it easily in the starting position. Or, better, have it always in the view even with dozens of columns of data... so that you just cannot escape the information no matter how you slide horizontally.

**Comment by ftrotter** [comment]
Ok, I see the new work which is left-aligned.. I have gone ahead and replaced it with a card based bootstrap interface that is fixed to the bottom of the screen. Using the fixed css, this error will follow the user even as they scroll around on the interface...
