### ISSUE TITLE
There doesn't appear to be a Zermelo:create command

### ISSUE THREAD

**Issue by kchapple** [CareSet/Zermelo#37]
Installing Zermelo, no command found. Error: "There are no commands defined in the "Zermelo" namespace."

Looked in ServiceProvider and doesn't define any commands. Perhaps this functionality got removed accidentally in a revision?

**Comment by ftrotter** [comment]
Just waiting. see https://github.com/CareSet/Zermelo/issues/24

**Comment by ftrotter** [comment]
I think this is now done.. and we can close this ticket.

**Comment by ftrotter** [comment]
It looks like the command is ,/artisan make:zermelo is that right?
