### ISSUE TITLE
Default Namespace is "Reports"

### ISSUE THREAD

**Issue by kchapple** [CareSet/Zermelo#38]
On step 3 of configuration, "Edit the file /app/Zermelo/YourNewReportName You must fill in a reasonable GetSQL() function that returns either a single SQL text string, or an array of SQL text strings."

Should the default report namespace be Reports or Zermelo?

**Comment by ftrotter** [comment]
Zermelo, in order to ensure we do not conflict with other report system, and to make it easier to use github to eventually sort out if other projects are adopting our library

**Comment by ftrotter** [comment]
Currently we are using the Report directory.. and I would love to move this to Zermelo.. but I can also be overruled.... 

would like to decide on the best thing in this sprint and either close this ticket and leave it as "Report" or move to "Zermelo"..

**Comment by kchapple** [comment]
This got lost, the default is still reports, but I agree it should be Zermelo

**Comment by ftrotter** [comment]
we now have dozens of instances of the Zermelo reporting engine on several servers. 
I do not want to change this from Reports. The ship has sailed. 

Lets discuss and confirm one way or another...

**Comment by ftrotter** [comment]
assuming /app/Reports/ is acceptable
