### ISSUE TITLE
CACHE_TIMEOUT is not respected

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#45]
The CACHE_TIMEOUT configuration variable being set to 0 should mean that although data is stored in the _cache table, it is always overwritten. 

This does not seem to be respected. 

Note: I do have multiple instances of the reporting engine on the same server using the same _cache database, but that should be a supported configuration...

The "real" ticket here is this: 

https://github.com/CareSet/Zermelo/issues/46

If we could just upgrade to this solution I would be very very happy...

**Comment by kchapple** [comment]
This has been fixed
