### ISSUE TITLE
Give full control of caching to the report

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#46]
All of the very serious frustrating debugging that I have dealt with in not only this version of the reporting engine, but all previous versions has been related to caching. The caching was not set the way I thought it was, I thought I had turned off caching but I had not. 

Caching is a killer feature for performance of very complex reports, but for developing reports and for all users that want to use the reporting engine as a "small data" browsing tool.. it is overkill and causes painful debugging headaches.. 

As a result, lets turn it entirely off by default. Lets remove the option to turn it on from the configuration files. I have added the following two functions to the report template

```
        /**
    * Should we enable the cache on this table?
    * This will improve the performance of very large and complex queries by only running the SQL once and then storing
    * the results in a dynamically creqted table in the _cache database.
    * But it also creates hard to debug update errors that are very confusing when changing GetSQL() contents.
    */
   public function isCacheEnabled(){
        return(false);
   }

        /**
    * How much time should pass (in seconds) before you update your _cache table for this report?
    * this only has an effect when isCacheEnabled is turned on.
    */
   public function howLongToCacheInSeconds(){
        return(600); //ten minutes by default
   }
```

Lets have the entire caching system pivot on those two functions. This way, when a person really wants the reports to be cached, they can do that for that report and that report only. 

Of course, the system should still be configured to write out its results into the _cache database dynamically named table, but it should always be overwriting that in the default mode. 

Does that make sense?

-FT

**Comment by kchapple** [comment]
This has been fixed by adding timeout and on/off toggle to cache report.
