### ISSUE TITLE
csv file name download should include MD5 from the contents of getCode

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#48]
The file name for the csv download (for now) should include the contents of the getCode() function, assuming they are not null. 

We will do lots of later improvements to the download functionality.. but for now that should be enough...

**Comment by kchapple** [comment]
Added getCode() to filename, tested by putting a string in URL after the / and click download.
![Screen Shot 2019-12-10 at 9 41 58 AM](https://user-images.githubusercontent.com/271809/70539688-0e45ed80-1b32-11ea-8c52-7b004255a6a1.png)
