### ISSUE TITLE
Create initial implementation of the bracket system (used to be "bolt") 

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#53]
This is a database abstraction method that allows the user to use a popup a window and select which instance of a structurally identically table should be selected from pre-selected list of possible options. 

This harder to explain in written form rather than show... 

https://drive.google.com/open?id=1ba3KtQ62e2ppXpcouOAHysMd0llDyTOF

I am not certain that we should implement this now, I think the bracketing system should be entirely functional without the use of brackets. But it is something important enough that I want to start accounting for it in the design...

**Comment by kchapple** [comment]
This was done
