### ISSUE TITLE
Lets have composer require just one meta package

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#55]
So far, we have four layout engines, tabular, graph, cards and "tree cards".

soon hopefully a Vega charting solution. We might also support a hard core JS timeline reporting engine. 

Given this, I think it does not make sense to take a piecemeal approach to installing Zermelo. 

We should have the main package "depend" on the various views, so that installing it would automatically add every type of report. Without a report extending the specific type of report, there is no reason not to install all of the reporting view systems. 

This should reduce the instructions for installation considerably as we add new view and report types...

**Comment by kchapple** [comment]
This has been done with zermelo_installer package.

**Comment by ftrotter** [comment]
There are some clunky things depending on how the installation goes down.. but it looks like the merger does work.. closing the ticket.
