### ISSUE TITLE
Annoying _cache table names

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#59]
The name of the cache table is currently something like:

Report_cd173ac1a01ebd40f847b25ac189c3d8

But it should be something like: 

YourClassNameHere_cd173ac1a01ebd40f847b25ac189c3d8

Which would let you much more easily debug things

**Comment by kchapple** [comment]
This has been fixed, We use the report name, up to 31 characters (because table names have a length limitation and we also have the hash at the end)
