### ISSUE TITLE
Composer Update does not update

### ISSUE THREAD

**Issue by tmccormi** [CareSet/Zermelo#64]
Attempts to solve #57 resulted in needing to tag and then update the ZermeloBladeTabular version.
The presumed method for getting the update: _composer update_ did not retrieve the new tagged 0.0.2
Manually using _composer require careset/zermelobladetabular_ at the root of the project worked.

Need to resolve the composer.json contents so an update works as expected.

**Comment by ftrotter** [comment]
This is ancient and can be closed
