### ISSUE TITLE
How do I prevent SQL injection? give me a shortcut to "quote"

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#7]
I am writing raw SQL for my reports, and I am accepting user input. 

I need to have a consistent way to prevent SQL injections. Whatever that way is needs to be clearly documented in the template code and how-to.

**Comment by siphu** [comment]
Can still use \DB::connection()->getPdo()->quote($values);

**Comment by ftrotter** [comment]
Wonderful. Lets create a function on the report object called "quote" that wraps that very large and hard to remember Laravel-esque query. So that report developers can just use:

$some_variable_q = $this->quote($some_variable); 

instead of 
$some_variable_q =  \DB::connection()->getPdo()->quote($some_variable);

Making quoting simpler will result in it being used more and generally improve the security of reports...

**Comment by ftrotter** [comment]
done.
