### ISSUE TITLE
Very large descriptions cause a 0 height table

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#73]
Table needs a minimum height to fix. 

How to replicate: create a report with a description that takes an entire html page (or more)... this will make the table disappear for now.

**Comment by kchapple** [comment]
Fix to reports that have large descriptions that caused the table to be hidden. Removed seemingly unnecessary resizeTable() function, and utilized increasing scrollY datatables setting and scrollCollapse datatables setting (#73)

Commit made on ZermeloBladeTabular to address this:
https://github.com/CareSet/ZermeloBladeTabular/commit/3b84fac5c85d69781d9f195c70d39b07ec50a525

**Comment by seanccsmith** [comment]
Very long descriptions can now be added without causing problems. Closing issue.
