### ISSUE TITLE
Northwind Test data has ? instead of apostrphe's displayed in names

### ISSUE THREAD

**Issue by tmccormi** [CareSet/Zermelo#78]
This is using my Vagrant Homestead install.

![questionmark](https://user-images.githubusercontent.com/285835/49664244-24dcd480-fa06-11e8-8f24-cc3304433feb.png)

**Comment by ftrotter** [comment]
I think this will be resolved by the feature insisting at the outset on proper character sets. However this needs to be tested.

**Comment by ftrotter** [comment]
Assuming this is a character_set bug.
