### ISSUE TITLE
"Download CSV" throws error on `StreamedResponse::header()`

### ISSUE THREAD

**Issue by piw** [CareSet/Zermelo#79]
The "Download CSV" function in Zermelo engine throws out an error:

`Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::header()`

It happens after the middleware is set up for sign-in authorization.
Possibly related to this StackOverflow discussion:
https://stackoverflow.com/questions/43593351/call-to-undefined-method-symfony-component-httpfoundation-responseheader

**Comment by kchapple** [comment]
This was resolved.
