### ISSUE TITLE
How to surface advanced error?

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#8]
Lets suppose I get invalid input, because of a malformed url, or because someone entered the wrong information to a form that feeds a report. 

How do I surface an "error" from within GetSQL that is appropriate for end user consumption? 

How do I surface the technical details of that error? Do I log it?

**Comment by siphu** [comment]
the easiest way to check ajax errors is to look at the 'network' tab in inspector (on chrome).
report will attempt to log to the console if an error comes up

**Comment by ftrotter** [comment]
I am not asking how to check errors on the network tab. That is fine for an developer who is working "on" the reporting engine, but not acceptable for a report builder working "with" a reporting engine or an end user. 

Right now, when the SQL query fails, the system fails silently. At a minimum, there needs to be something on the report that says "there was an error on the backend". Preferrably, that should be extended to "There was an error on the backend and it was 'XYZ'" please pass that error message along to the administrators". Obviously, the actual contents of the error are a security risk to pass on. So there should be errors like "there was a problem with the SQL of this report"... etc etc..

**Comment by ftrotter** [comment]
Very specifically, when a SQL based error occurs in the current reporting engine, an HTML file is created, as the backend crashes and resorts to Laravels error display engine. 

The SQL error needs to be captured, at a minimum and returned as an error coded in JSON, so that it can be processed as data by any front end. There should be, on EVERY JSON report, an is_error = field that can be checked by the front end. 

if is_error = false... then it knows to use the default display system. 
if is_error = true.. then it knows that an error is occured,, and then it should display second field called error_div...

And depending on a configuration value called "is_show_revealing_error_messages" the contents should either say "Shoot, something when wrong with the underlying SQL powering this report, please contact support" or "Shoot, something went wrong with underlying SQL, here is the SQL, and here is the SQL error message that I got".

Both of these messages should be based on templates that live inside the configuration file, so that they can be customized without changing anything except configuration.

**Comment by ftrotter** [comment]
Note, I realize that if the you set the content type of the ajax request to json then laravel will automatically return json error messages, which can then be parsed properly by the front end..

I have fixed this somewhat, but some crashing errors still do not reply with json errors and so it still does not work.. but it is good enough to lower the priority on this issue

**Comment by ftrotter** [comment]
This seems to work correctly now!! closing.
