### ISSUE TITLE
_GET parameters that modify the data do not modify the cache table/data download 

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#85]
Some get parameters are not intended to modify the cache table. 
sorting, searching filtering etc etc etc. Are all "ignorable" from the data cache perspective. 

But custom _GET parameters should modify the contents of the cache table (and the cache md5 instance) 

This will allow html forms in the description to power different permutations of the data correctly. 

The CSV needs to be based on the SQL that was actually just run, and not the cached data..

**Comment by kchapple** [comment]
This is now fixed. Use setDefaultSortOrder() in tabular report getSQL() to set a default sort order. Order and filters on the UI do not affect cache, but parameters passed in URL (like the date rages on NorthwindOrderReport example), and data view options **DO** affect cache.
