### ISSUE TITLE
asset already exists. Do you want to replace it? Upgrades are painful.

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#87]
When updating an existing instance of zermelo, it is convenient to simple remove zermelo from composer.json and then do a composer update to get rid of it.

But then when you install Zermelo again, along with the various viewers. It will see that the previous installation exists and ask: 

  The [bootstrap/css/bootstrap-reboot.min.css.map] asset already exists. Do you want to replace it? (yes/no) [no]:

etc etc again and again. 
The problem with this is that if those assets have actually changed then we really do want them to be updated. And if they have not been changed, then why on earth is the installation even asking about them. 

The right behavior is to say "hey this thing I want to install is different than what you have, so I should install right [yes]:" so that the default is to upgrade when there is an upgrade, but to be silent and do nothing if there is actually no underlying change.

**Comment by kchapple** [comment]
I was wondering if it might be most reliable for each view to have their own asset folder, and also only overwrite files if they are differnt? I can see how it could get messy if and end user upgrades some views and not others, and the dependencies get out of whack. If each view had it's own set of assets then we'd avoid that, but also have some redundancy.

**Comment by ftrotter** [comment]
We should discuss good ways to handle user modifications... but for the purposes of this bug, I just want to not have to say 'yes' or 'no' many times during the upgrade.

**Comment by kchapple** [comment]
I added checks, run md5 on file contents, compare hashes and don't ask user to overwrite if they are identical.
