### ISSUE TITLE
upgrade problems

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#92]
when performing an upgrade, the old version of /config/zermelo.php will. be missing stuff and it will choke the 

composer update

command. That should not happen. It should update zermelo and the when loading the report complain about missing config parameters.

Similarly, zermelo should not be trying to load report classes during composer update. the update also crashed when the functions in the reports were wrong. That does not belong in the composer update stage.. right?

If this is intentional then the error messages need to improve.

**Comment by kchapple** [comment]
Fixed in:
[master 41e2477] Fixed installation issues where syntax errors in reports would choke composer update, also check if current/old config file is missing new/required settings(#92)

**Comment by ftrotter** [comment]
its like a breath of fresh air.
