### ISSUE TITLE
problems with column names crash with aoColumns[srcCol] is undefined

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#94]
problematic column names sometimes crashes whole report. 

There is a javascript error of aoColumns[srcCol] is undefined on the front end. 
This is due to no columns being listed in both of the json "columns" area. 

This needs two solutions. (maybe more)

1. there are not that many data points in either the summary json or the data json. If these values are missing, null or of the wrong type. There should be an "in UI" error message that says: 

* The json being generated is deficient, and why
*  links to the json source so that it can be debugged quickly. 

The only error that should be handled differently is when the data returns nothing. Then it should just say, "the backed did not return any results for this report" because that is a sometimes-valid case where the json does not look right, from a deployment perspective. All other deviations from the basic expected JSON need to generate a report-developer friendly error message. this work needs to be done now for the tablular data reports, and hopefully done in a way that makes it simple to check for things in the graph version later. 

2. Obviously, getting problematic values for columns or problematic column names or whatever is the root cause here needs to be fixed on the back end so that column names are put forward.

**Comment by ftrotter** [comment]
This looks like it is actually a duplicate of #93 

https://github.com/ftrotter/LoreCommander/blob/master/app/Reports/CardSearch.php

**Comment by ftrotter** [comment]
I think this is because they are using strange characters in the first row of results...

**Comment by ftrotter** [comment]
Yep, this SQL fixed the problem: 

UPDATE `cardface` SET `type_line` = REPLACE( type_line, '—','-')

So it is all about strange characters in the first row of results...

**Comment by kchapple** [comment]
@ftrotter I'm not able to reproduce, this is what I see on my dev system. I wonder what Collation and character set you're using on your DB? I tried with ascii_general_ci, utf8_general_ci, and utf8mb4_general_ci and none of them reproduced the error. I imported the file using phpmyadmin on the utf8 character set setting. 

I know the summary does look at the first row of data, I think to get the column names for row-mapping, so perhaps that process of getting the column names can be done a different way, or error checked. 

![Screen Shot 2019-07-12 at 10 02 36 AM](https://user-images.githubusercontent.com/271809/61133865-44e8e080-a48c-11e9-8bbd-92e19563202b.png)

**Comment by ftrotter** [comment]
OK, I think I typically use latin1_swedish_ci just because that seems to be the default. The test data specifically has a latin1 charset and I suspect that you will need to honor that to replicate. 

But I think it is reasonable that the tool require reasonable character settings. So requiring a utf8 permutation as a default setting makes sense to me as a potential solution in the end.. but we need to verify that this actually addresses the problem. 

First, the weird character has to be in the first row of data being pulled back. If it is not the in the first row then the problem does not happen. This makes me suspect that the problem is occurring in php and not in MySQL at all. 

Once you have tested with "latin1" etc, it would see about taking a non-ascii character and then using a ascii-only mysql data type in the cache table and see if you can replicate the error that way.

If you still cannot replicate I will find a way to get you a instance of a server where I know that I have had the problem...

-FT

**Comment by ftrotter** [comment]
closing this as hopefully fixed by charset check which is now #101
